name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v3

      # Устанавливаем JDK 11 (Adoptium Temurin — современный дистрибутив)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Даём права на выполнение gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Запускаем тестируемое приложение (SUT) в фоне
      - name: Start SUT
        run: java -jar ./artifacts/app-order.jar &

      # Ждём, чтобы SUT успел подняться (например, 10 секунд)
      - name: Wait for SUT to start
        run: sleep 10

      # Запускаем автотесты через Gradle
      - name: Build with Gradle and run tests
        run: ./gradlew test --info -Dselenide.headless=true

